version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: agenda_db
      MARIADB_USER: app_user
      MARIADB_PASSWORD: E7650190
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: